### ISSUE TITLE
编译打包不通过

### ISSUE THREAD

**Issue by micrologic** [drakeet/TimeMachine#49]
Failed to finalize session : INSTALL_FAILED_TEST_ONLY: installPackageLI

**Comment by drakeet** [comment]
你提供的信息完全不够，请学会提问的方式。
另外，TimeMachine 只支持使用 Android Studio 2.4 或 3.0 版本才能保证正常编译安装，理论上不支持 Android Studio 2.3.

**Comment by drakeet** [comment]
测试了下，很尴尬，TimeMachine 目前只支持 Android Studio 2.4，却不支持 3.0 canary 版本，因此可能需要等待 3.0 稳定后，再适配下。

**Comment by drakeet** [comment]
我不知道你使用的 Android Studio 是哪个版本，如果提问，请提供你使用的 IDE 版本或其他相关内容信息。

**Comment by micrologic** [comment]
ok.向您学习了。我现在描提供一下完整的信息。
1.Android studio 当我点击run的时候，弹框提示，title为："Application Installation Failed" ，content是：“Installation falled with message Failed to finalize session : INSTALL_FAILED_TEST_ONLY: installPackageLI. It's possible that is issue....and then re-installing...”etc.你可以猜到省略号说大概说的是什么信息了。
2.我点击上述弹框确认，EventLog信息是：
`
下午12:14	Executing tasks: [:transformer:assembleDebug]

下午12:14	Gradle build finished in 5s 283ms

下午12:14	Failed to finalize session : INSTALL_FAILED_TEST_ONLY: installPackageLI

下午12:18	Session 'transformer': Error Installing APKs
`
如上。
不过你凭借出色的经验已经猜出了，我确实用的是Android studio 2.3.

**Comment by drakeet** [comment]
Android Studio 2.3 是明确不支持的，因为 TimeMachine 使用了 Android 官方提供的 desugar 来支持 Java 8，该功能只在 2.4 或以上才有，但由于 3.0 又改变了一些行为，目前还不能直接兼容，待适配。

**Comment by micrologic** [comment]
我之所有没有告知操作系统, IDE, gradle, SDK等版本信息，是因为我用的版本都还是在新的基础上比较稳定的版本。就比如我用的是Android studio 2.3.1 stable channel,应该算是比较新的版本吧，因此我判断这个编译打包不通过，应该与目前这个IDE的版本无关吧。只是这个问题的答案刚好是跟IDE的版本有关系而已，GitHub上提的这么多Issue也没有见过任何一个问题都带上各种版本信息吧。向您学习一下，学会提问是应该是什么样的提问？谢谢！

**Comment by drakeet** [comment]
关于提问的方式：

无论如何，你应该提供你的问题相关的环境状况，例如你使用了某个库出现了运行时问题，你应该提供你使用的手机设备型号、系统版本；如果你遇到了像今天这样编译不过，那应该提供你的编译工具版本；

除了以上最基本的之外，你应该提供错误或问题的复现路径、尽可能详细的描述、相关信息。

另外，很重要的还有，你必须是经过自己思考和努力一番后才允许提问，而不是遇到问题立马伸手。因此，你需要描述你在提问之前，自己经过了哪些思考，经过了哪些努力、探索，结果呢？这样别人才能接手你的问题，了解到你进展到哪一步等等。

**Comment by micrologic** [comment]
thx!

**Comment by drakeet** [comment]
Fixed: https://github.com/drakeet/TimeMachine/commit/97fc99fcb338577eba05d5a4e88901f4e8573422
