### ISSUE TITLE
RecyclerView的item点击监听和item中的view的监听重复

### ISSUE THREAD

**Issue by zzw3239** [drakeet/TimeMachine#51]
如题，比如点击item中某个Button会先触发item的监听，然后触发Button的监听，导致Button和item的监听都被执行了。

**Comment by drakeet** [comment]
这个问题和我的项目似乎没有什么关系。另外 Android 的手势事件是不会导致你说的事情发生的。

**Comment by zzw3239** [comment]
嗯，和项目没什么关系。我也是用了您这种RecyclerView的Item点击监听，在我说的这种情况下是会有不足之处。

**Comment by drakeet** [comment]
并不会，你说的是错的，请先做了验证再说。另外，和本项目无关的主题请不要在此讨论，有问题的话你可以给我写邮件。

**Comment by drakeet** [comment]
Android 手势分发机制并不是如你想的那样。你可以先了解清楚 Android 的手势分发机制和做过实验后再说。
